'use strict';

const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');

const ROOT = path.resolve(__dirname, '../../..');
const HELPER_PATH = path.join(ROOT, 'scripts/i2-orca-runtime-smoke.js');
const WORKFLOW_PATH = path.join(ROOT, '.github/workflows/image-validation.yml');
const SOURCE = fs.readFileSync(HELPER_PATH, 'utf8').replace(/\r\n?/g, '\n');
const WORKFLOW = fs.readFileSync(WORKFLOW_PATH, 'utf8').replace(/\r\n?/g, '\n');
const smoke = require(HELPER_PATH);

const ID = `sha256:${'b'.repeat(64)}`;

function step(id, source = WORKFLOW) {
    const start = source.indexOf(`        id: ${id}`);
    assert.notEqual(start, -1, `missing ${id}`);
    const end = source.indexOf('\n      - name:', start);
    return source.slice(start, end < 0 ? source.length : end);
}

function helperContract(source) {
    for (const anchor of [
        "spawnSync('docker', args,", "spawnSync('/usr/local/bin/orca-slicer', args,",
        'shell: false', 'maxBuffer: MAX_OUTPUT_BYTES', 'timeout = DOCKER_TIMEOUT_MS',
        "'--pull', 'never'", "'--network', 'none'", "'--cap-drop', 'ALL'",
        "'--security-opt', 'no-new-privileges'", "'--read-only'",
        'rw,nosuid,nodev,noexec,size=256m,uid=${uid},gid=${gid},mode=0700',
        'validateImageId(imageId)', 'numeric <= 0', "'container', 'create'",
        '${VALIDATION_LABEL}=true', '${IMAGE_LABEL}=${exactImageId}',
        '\n    assertOwned(record, containerId, imageId);\n',
        "'--entrypoint', '/usr/bin/node'", "runOrca(['--help'], 60_000)",
        "'--load-settings', settings", "'--slice', '0'", 'synthetic-cube.stl',
        'OrcaSlicer-2\\.3\\.1', 'generated by OrcaSlicer 2\\.3\\.1',
        'MAX_GCODE_PREFIX_BYTES', "exit(33)", "stat.size > 32 * 1024 * 1024",
        'classification=success'
    ]) assert.ok(source.includes(anchor), `missing ${anchor}`);
    assert.doesNotMatch(source, /\bshell\s*:\s*true|\beval\s*\(|\/bin\/(?:ba)?sh|\b999\b|\/etc\/passwd/);
}

test('Orca smoke accepts only positive dynamic identity and an immutable image ID', () => {
    assert.doesNotThrow(() => new Function(smoke.ORCA_CONTAINER_SCRIPT));
    assert.equal(smoke.parsePositiveEnvironmentId('1001', 'uid'), 1001);
    for (const value of ['', '0', '-1', '1\n2', ' 1001', '1001 ']) {
        assert.throws(() => smoke.parsePositiveEnvironmentId(value, 'uid'));
    }
    const args = smoke.buildCreateArgs('orca-probe', ID, '1001', '1002');
    assert.deepEqual(args.slice(0, 4), ['container', 'create', '--pull', 'never']);
    assert.deepEqual(args.slice(-4), ['/usr/bin/node', ID, '-e', smoke.ORCA_CONTAINER_SCRIPT]);
    for (const token of ['--network', 'none', '--cap-drop', 'ALL', '--security-opt',
        'no-new-privileges', '--read-only', '--pids-limit', '256']) assert.ok(args.includes(token));
    assert.ok(args.includes('/tmp:rw,nosuid,nodev,noexec,size=256m,uid=1001,gid=1002,mode=0700'));
    assert.ok(args.includes(`${smoke.IMAGE_LABEL}=${ID}`));
    assert.throws(() => smoke.buildCreateArgs('orca-probe', 'local/image:latest', '1001', '1002'));
});

test('synthetic cube is closed, consistently wound, and has exact nonzero normals', () => {
    assert.equal(smoke.SYNTHETIC_TRIANGLES.length, 12);
    assert.equal(smoke.SYNTHETIC_STL, smoke.buildSyntheticStl());
    const edges = new Map();
    for (const { normal, vertices } of smoke.SYNTHETIC_TRIANGLES) {
        assert.equal(Math.hypot(...normal), 1);
        const [a, b, c] = vertices;
        const ab = b.map((value, index) => value - a[index]);
        const ac = c.map((value, index) => value - a[index]);
        const cross = [
            ab[1] * ac[2] - ab[2] * ac[1],
            ab[2] * ac[0] - ab[0] * ac[2],
            ab[0] * ac[1] - ab[1] * ac[0]
        ];
        assert.ok(cross.reduce((sum, value, index) => sum + value * normal[index], 0) > 0);
        for (const [from, to] of [[a, b], [b, c], [c, a]]) {
            const directed = `${from.join(',')}>${to.join(',')}`;
            const reverse = `${to.join(',')}>${from.join(',')}`;
            if (edges.has(reverse)) edges.set(reverse, edges.get(reverse) + 1);
            else edges.set(directed, 1);
        }
    }
    assert.equal(edges.size, 18);
    assert.ok([...edges.values()].every((count) => count === 2));
    assert.doesNotMatch(smoke.SYNTHETIC_STL, /facet normal 0 0 0/);
});

test('Orca smoke result is exact, bounded, and independently classified', () => {
    assert.doesNotThrow(() => smoke.parseSmokeResult({
        status: 0, stdout: smoke.SUCCESS_MARKER, stderr: ''
    }));
    for (const [status, message] of [[20, 'orca_help_execution_failure'],
        [21, 'orca_help_contract_failure'], [30, 'orca_slice_execution_failure'],
        [31, 'orca_slice_output_count_failure'], [32, 'orca_slice_output_contract_failure'],
        [33, 'orca_slice_content_failure'],
        [39, 'orca_smoke_internal_failure'], [99, 'orca_smoke_failure']]) {
        assert.throws(() => smoke.parseSmokeResult({ status, stdout: '', stderr: '' }),
            new RegExp(message));
    }
    assert.throws(() => smoke.parseSmokeResult({ status: 0, stdout: 'PASS\n', stderr: '' }),
        /orca_smoke_output_failure/);
    assert.throws(() => smoke.parseSmokeResult({
        status: 0, stdout: smoke.SUCCESS_MARKER, stderr: 'warning'
    }), /orca_smoke_output_failure/);
});

function inspectRecord(containerId, imageId = ID, validation = 'true', expected = imageId) {
    return {
        status: 0,
        stdout: `${JSON.stringify(containerId)}|${JSON.stringify(imageId)}|` +
            `${JSON.stringify(validation)}|${JSON.stringify(expected)}\n`,
        stderr: ''
    };
}

function absent(reference) {
    return { status: 1, stdout: '', stderr: `Error: No such object: ${reference}\n` };
}

test('ownership parsing rejects foreign labels and exact-ID cleanup never removes by name', () => {
    const containerId = 'c'.repeat(64);
    const owned = smoke.parseInspectResult(inspectRecord(containerId), containerId);
    assert.doesNotThrow(() => smoke.assertOwned(owned, containerId, ID));
    for (const record of [
        inspectRecord(containerId, ID, 'false', ID),
        inspectRecord(containerId, ID, 'true', `sha256:${'d'.repeat(64)}`),
        inspectRecord(containerId, `sha256:${'d'.repeat(64)}`, 'true', ID)
    ]) {
        assert.throws(() => smoke.assertOwned(
            smoke.parseInspectResult(record, containerId), containerId, ID),
        /container_ownership_failure/);
    }
    assert.deepEqual(smoke.buildRemoveArgs(containerId),
        ['container', 'rm', '--force', containerId]);
    assert.throws(() => smoke.buildRemoveArgs('orca-probe'));
});

test('name reuse and foreign ownership are fail-closed without deleting the foreign container', (t) => {
    const containerId = 'c'.repeat(64);
    const outputPath = path.join(os.tmpdir(), `.orca-smoke-output-${process.pid}-${Date.now()}`);
    fs.writeFileSync(outputPath, '');
    t.after(() => fs.rmSync(outputPath, { force: true }));
    const env = {
        I2_ORCA_PROBE_NAME: 'orca-probe',
        EXPECTED_IMAGE_ID: ID,
        SERVICE_UID: '1001',
        SERVICE_GID: '1002',
        GITHUB_OUTPUT: outputPath
    };

    const runScenario = (responses) => {
        const calls = [];
        const docker = (args) => {
            calls.push(args);
            const response = responses.shift();
            assert.ok(response, `unexpected docker call ${args.join(' ')}`);
            return typeof response === 'function' ? response(args) : response;
        };
        assert.throws(() => smoke.runSmoke(env, docker));
        assert.equal(responses.length, 0);
        return calls;
    };

    const foreignCleanupCalls = runScenario([
        absent('orca-probe'),
        { status: 0, stdout: `${containerId}\n`, stderr: '' },
        inspectRecord(containerId),
        { status: 0, stdout: smoke.SUCCESS_MARKER, stderr: '' },
        inspectRecord(containerId, ID, 'false', ID),
        absent('orca-probe')
    ]);
    assert.equal(foreignCleanupCalls.filter((args) => args[1] === 'rm').length, 0);

    const nameReuseCalls = runScenario([
        absent('orca-probe'),
        { status: 0, stdout: `${containerId}\n`, stderr: '' },
        inspectRecord(containerId),
        { status: 0, stdout: smoke.SUCCESS_MARKER, stderr: '' },
        inspectRecord(containerId),
        { status: 0, stdout: `${containerId}\n`, stderr: '' },
        absent(containerId),
        inspectRecord('d'.repeat(64), ID, 'false', ID)
    ]);
    const removals = nameReuseCalls.filter((args) => args[1] === 'rm');
    assert.equal(removals.length, 1);
    assert.equal(removals[0].at(-1), containerId);
});

test('workflow binds Orca smoke to exact identity, cleanup, and final enforcement', () => {
    const orca = step('orca_cli_smoke');
    const cleanup = step('exact_cleanup');
    const final = step('final_enforcement');
    assert.match(orca, /if: \$\{\{ steps\.runtime_identity\.outcome == 'success' \}\}/);
    assert.match(orca, /continue-on-error: true/);
    assert.match(orca, /EXPECTED_IMAGE_ID: \$\{\{ steps\.image_identity\.outputs\.image_id \}\}/);
    assert.match(orca, /SERVICE_UID: \$\{\{ steps\.runtime_identity\.outputs\.uid \}\}/);
    assert.match(orca, /SERVICE_GID: \$\{\{ steps\.runtime_identity\.outputs\.gid \}\}/);
    assert.match(orca, /node scripts\/i2-orca-runtime-smoke\.js/);
    assert.match(cleanup, /I2_ORCA_PROBE_NAME/);
    assert.match(final, /ORCA_CLI_SMOKE_OUTCOME/);
    assert.match(final, /ORCA_CLI_SMOKE_CLASSIFICATION/);
    assert.match(final, /failures\.push\('orca_cli_smoke_failure'\)/);
    helperContract(SOURCE);
});

test('Orca smoke weakening mutations are rejected by the local contract', async (t) => {
    const mutations = [
        ['network restored', "'--network', 'none'", "'--network', 'bridge'"],
        ['floating image admitted', 'validateImageId(imageId)', 'imageId'],
        ['shell enabled', 'shell: false', 'shell: true'],
        ['root identity admitted', 'numeric <= 0', 'numeric < 0'],
        ['world-writable tmpfs', 'mode=0700', 'mode=0777'],
        ['synthetic slice removed', "'--slice', '0'", "'--info'"],
        ['output bound removed', 'stat.size > 32 * 1024 * 1024', 'false'],
        ['version assertion removed', 'OrcaSlicer-2\\.3\\.1', 'OrcaSlicer'],
        ['ownership assertion removed', '    assertOwned(record, containerId, imageId);', '    void record;']
    ];
    for (const [name, from, to] of mutations) await t.test(name, () => {
        assert.ok(SOURCE.includes(from), `missing ${from}`);
        assert.throws(() => helperContract(SOURCE.replace(from, to)));
    });
});
