'use strict';

const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const ROOT = path.resolve(__dirname, '../../..');
const RUNNER_PATH = path.join(ROOT, 'scripts/i2-orca-runtime-smoke.js');
const SUPPORT_PATHS = [
    'scripts/i2-orca-runtime-smoke-fixture.js',
    'scripts/i2-orca-runtime-smoke-container-script.js',
    'scripts/i2-orca-runtime-smoke-contract.js'
].map((relativePath) => path.join(ROOT, relativePath));
const WORKFLOW_PATH = path.join(ROOT, '.github/actions/exact-image-gate/action.yml');
const RUNNER_SOURCE = fs.readFileSync(RUNNER_PATH, 'utf8').replace(/\r\n?/g, '\n');
const SUPPORT_SOURCES = SUPPORT_PATHS.map((filePath) =>
    fs.readFileSync(filePath, 'utf8').replace(/\r\n?/g, '\n'));
const SOURCE = [RUNNER_SOURCE, ...SUPPORT_SOURCES].join('\n');
const WORKFLOW = fs.readFileSync(WORKFLOW_PATH, 'utf8').replace(/\r\n?/g, '\n');

function step(id, source = WORKFLOW) {
    const start = source.indexOf(`        id: ${id}`);
    assert.notEqual(start, -1, `missing ${id}`);
    const end = source.indexOf('\n      - name:', start);
    return source.slice(start, end < 0 ? source.length : end);
}

function assertNamedFunctionsAreBounded(filePath, source) {
    const lines = source.split('\n');
    const starts = lines.flatMap((line, index) =>
        /^(?:async )?function [A-Za-z]/.test(line) ? [index] : []);
    for (const [position, start] of starts.entries()) {
        const end = starts[position + 1] ?? lines.length;
        assert.ok(end - start <= 60,
            `${path.basename(filePath)}:${start + 1} spans ${end - start} physical lines`);
    }
}

function helperContract(source) {
    for (const anchor of [
        "spawnSync('docker', args,", "spawnSync('/usr/local/bin/orca-slicer', args,",
        'shell: false', 'maxBuffer: MAX_OUTPUT_BYTES', 'timeout = DOCKER_TIMEOUT_MS',
        'const MAX_ORCA_OUTPUT_BYTES = 1024 * 10000;',
        'maxBuffer: MAX_ORCA_OUTPUT_BYTES', "emitFailure('slice', sliced)",
        "'--pull', 'never'", "'--network', 'none'", "'--cap-drop', 'ALL'",
        "'--security-opt', 'no-new-privileges'", "'--read-only'",
        'rw,nosuid,nodev,noexec,size=256m,uid=${uid},gid=${gid},mode=0700',
        'validateImageId(imageId)', 'numeric <= 0', "'container', 'create'",
        '${VALIDATION_LABEL}=true', '${IMAGE_LABEL}=${exactImageId}',
        'contract.assertOwned(record, containerId, imageId);',
        "'--entrypoint', '/usr/bin/node'", "runOrca(['--help'], 60_000)",
        "require('/app/services/slice/profiles')",
        "require('/app/services/slice/engine')",
        "require('/app/services/slice/profile-snapshot')",
        "createRuntimeSlicerProfile(\n        'orca', snapshots.baseConfigFile, 'FDM', 0.2, '20%', workspace)",
        "snapshotProfileSelection('orca'",
        "profile.layer_gcode !== ''",
        "profile.use_relative_e_distances !== '1'",
        "profile.layer_change_gcode !== 'G92 E0'",
        "throw new Error('machine_profile_extrusion_contract')",
        "const slicerArgs = buildSlicerCommandArgs(",
        'assertScratchContainedPath:', 'assertContainedPath:',
        "throw new Error('runtime_profile_escape')",
        "void executeSmoke().catch(() => exit(39));",
        'function prepareSmokeDirectories()', 'function assertHelpContract()',
        'function createSmokeWorkspace()', 'async function prepareSliceInvocation()',
        'function runSliceProbe(slicerArgs)', 'function assertGeneratedGcode()',
        "slicerArgs[arrangeIndex + 1] !== '1'", "slicerArgs[orientIndex + 1] !== '0'",
        'const sliced = runOrca([...slicerArgs, model]',
        'synthetic-pre-rotated-asymmetric-prism.stl',
        'OrcaSlicer-2\\.3\\.1', 'generated by OrcaSlicer 2\\.3\\.1',
        '!hasPositiveExtrusionMove(prefix)', ';BEFORE_LAYER_CHANGE',
        'Number(extrusion[1]) > 0',
        "!/^M83(?:\\s|;|$)/m.test(prefix)", "^M82(?:\\s|;|$)",
        'MAX_GCODE_PREFIX_BYTES', "exit(33)", "stat.size > 32 * 1024 * 1024",
        'classification=success'
    ]) assert.ok(source.includes(anchor), `missing ${anchor}`);
    assert.doesNotMatch(source, /\bshell\s*:\s*true|\beval\s*\(|\/bin\/(?:ba)?sh|\b999\b|\/etc\/passwd/);
}

test('workflow binds Orca smoke to exact identity, cleanup, and final enforcement', () => {
    const orca = step('orca_cli_smoke');
    const cleanup = step('exact_cleanup');
    const final = step('final_enforcement');
    assert.match(orca, /if: \$\{\{ steps\.runtime_identity\.outcome == 'success' \}\}/);
    assert.match(orca, /continue-on-error: true/);
    assert.match(orca, /EXPECTED_IMAGE_ID: \$\{\{ steps\.image_identity\.outputs\.image_id \}\}/);
    assert.match(orca, /SERVICE_UID: \$\{\{ steps\.runtime_identity\.outputs\.uid \}\}/);
    assert.match(orca, /SERVICE_GID: \$\{\{ steps\.runtime_identity\.outputs\.gid \}\}/);
    assert.match(orca, /node scripts\/i2-orca-runtime-smoke\.js/);
    assert.match(cleanup, /I2_ORCA_PROBE_NAME/);
    assert.match(final, /ORCA_CLI_SMOKE_OUTCOME/);
    assert.match(final, /ORCA_CLI_SMOKE_CLASSIFICATION/);
    assert.match(final, /failures\.push\('orca_cli_smoke_failure'\)/);
    helperContract(SOURCE);
});

test('Orca smoke is split into bounded builders and a thin orchestration runner', () => {
    const containerBuilder = require(SUPPORT_PATHS[1]);
    const smoke = require(RUNNER_PATH);
    for (const [filePath, source] of [
        [RUNNER_PATH, RUNNER_SOURCE],
        ...SUPPORT_PATHS.map((filePath, index) => [filePath, SUPPORT_SOURCES[index]])
    ]) {
        assert.ok(source.split('\n').length <= 250,
            `${path.basename(filePath)} exceeds 250 physical lines`);
        assertNamedFunctionsAreBounded(filePath, source);
    }
    assert.equal(containerBuilder.buildOrcaContainerScript(), smoke.ORCA_CONTAINER_SCRIPT);
    assert.match(RUNNER_SOURCE, /function runSmoke\(/);
    assert.match(RUNNER_SOURCE, /spawnSync\('docker', args,/);
    assert.doesNotMatch(RUNNER_SOURCE, /String\.raw|spawnSync\('\/usr\/local\/bin\/orca-slicer'/);
    assert.match(SUPPORT_SOURCES[1], /function buildOrcaContainerScript\(\)/);
});

test('Orca smoke weakening mutations are rejected by the local contract', async (t) => {
    const mutations = [
        ['network restored', "'--network', 'none'", "'--network', 'bridge'"],
        ['floating image admitted', 'validateImageId(imageId)', 'imageId'],
        ['shell enabled', 'shell: false', 'shell: true'],
        ['root identity admitted', 'numeric <= 0', 'numeric < 0'],
        ['world-writable tmpfs', 'mode=0700', 'mode=0777'],
        ['synthetic slice removed', 'const sliced = runOrca([...slicerArgs, model]',
            'const sliced = runOrca([model]'],
        ['shared command policy bypassed', 'const slicerArgs = buildSlicerCommandArgs(',
            'const slicerArgs = bypassedCommandBuilder('],
        ['placement disabled', "slicerArgs[arrangeIndex + 1] !== '1'",
            "slicerArgs[arrangeIndex + 1] !== '0'"],
        ['orientation restored', "slicerArgs[orientIndex + 1] !== '0'",
            "slicerArgs[orientIndex + 1] !== '1'"],
        ['output bound removed', 'stat.size > 32 * 1024 * 1024', 'false'],
        ['zero extrusion admitted', 'Number(extrusion[1]) > 0', 'Number(extrusion[1]) >= 0'],
        ['model-layer marker removed', ';BEFORE_LAYER_CHANGE', ';IGNORED_LAYER_CHANGE'],
        ['positive extrusion proof bypassed', '!hasPositiveExtrusionMove(prefix)', 'false'],
        ['relative G-code proof removed', "!/^M83(?:\\s|;|$)/m.test(prefix)", 'false'],
        ['native output bound removed', 'maxBuffer: MAX_ORCA_OUTPUT_BYTES', 'maxBuffer: Infinity'],
        ['version assertion removed', 'OrcaSlicer-2\\.3\\.1', 'OrcaSlicer'],
        ['production profile generator bypassed',
            "createRuntimeSlicerProfile(\n        'orca', snapshots.baseConfigFile, 'FDM', 0.2, '20%', workspace)",
            'Promise.resolve(baseProcessProfile)'],
        ['absolute extrusion reset guard removed', "profile.layer_gcode !== ''", 'false'],
        ['relative extrusion guard removed',
            "profile.use_relative_e_distances !== '1'", 'false'],
        ['machine layer reset guard removed',
            "profile.layer_change_gcode !== 'G92 E0'", 'false'],
        ['scratch profile containment removed', 'assertScratchContainedPath:', 'unsafeScratchPath:'],
        ['runtime profile containment removed', 'assertContainedPath:', 'unsafeContainedPath:'],
        ['async failure handling removed',
            "void executeSmoke().catch(() => exit(39));", 'void executeSmoke();'],
        ['ownership assertion removed', 'contract.assertOwned(record, containerId, imageId);',
            'void record;']
    ];
    for (const [name, from, to] of mutations) await t.test(name, () => {
        assert.ok(SOURCE.includes(from), `missing ${from}`);
        assert.throws(() => helperContract(SOURCE.replace(from, to)));
    });
});
