'use strict';

const assert = require('node:assert/strict');
const { describe, it } = require('node:test');

const {
    BAMBU_PRINT_TIME_PATTERNS,
    GCODE_METRIC_ERROR_CODES,
    GcodeMetricsError,
    PRINT_TIME_PATTERNS,
    PRINT_TIME_PATTERNS_BY_ENGINE,
    parseDurationText,
    parseGcodeMetricsStrict,
    resolvePrintTimePatterns,
    sumNumericList
} = require('../../../app/services/slice/gcode-metrics');

const ORCA_231_GCODE = [
    '; generated by OrcaSlicer 2.3.1',
    '; model printing time: 2h 24m 12s; total estimated time: 2h 29m 41s',
    'M73 P0 R144',
    'M73 P1 R143',
    'G90',
    'M83',
    'G1 X10.5 Y10.5 Z0.2 F3000',
    'G1 X20.5 Y10.5 E0.9231 F1800',
    '; filament used [mm] = 12764.31',
    '; filament used [cm3] = 30.71',
    '; filament used [g] = 38.4',
    '; total filament used [g] = 38.4',
    '; estimated printing time (normal mode) = 2h 24m 12s',
    ''
].join('\n');

const PRUSA_281_GCODE = [
    '; generated by PrusaSlicer 2.8.1+linux-x64',
    'M73 P0 R97',
    'G1 X10 Y10 E0.5',
    '; filament used [mm] = 8123.4',
    '; filament used [g] = 24.22',
    '; estimated printing time (normal mode) = 1h 37m 5s',
    ''
].join('\n');

const PRUSA_ZERO_GRAMS_GCODE = [
    '; generated by PrusaSlicer 2.8.1+linux-x64',
    'M73 P0 R2',
    'G1 X10 Y10 E0.5',
    '; filament used [mm] = 1359.69',
    '; filament used [cm3] = 3.27',
    '; total filament used [g] = 0.00',
    ''
].join('\n');

const BAMBU_2862_GCODE = [
    '; BambuStudio 02.08.02.61',
    '; model printing time: 5m 38s; total estimated time: 11m 54s',
    'M73 P0 R6',
    'G90',
    'G1 X10.5 Y10.5 Z0.2 F3000',
    '; total filament length [mm] : 241.20',
    '; total filament volume [cm^3] : 0.58',
    '; total filament weight [g] : 0.72',
    ''
].join('\n');

describe('SZ-B2 strict G-code metrics', () => {
    it('reads Orca 2.3.1 M73 time, mass, length, and winning pattern identity exactly as before', () => {
        // Orca keeps the historical ranking: M73 P0 R144 wins (8640 s), so the
        // published Orca numbers stay byte-identical to the pre-overhaul output.
        for (const options of [undefined, { engine: 'orca' }]) {
            const metrics = parseGcodeMetricsStrict(ORCA_231_GCODE, options);
            assert.equal(metrics.filament_used_g, 38.4);
            assert.equal(metrics.print_time_seconds, 8640);
            assert.equal(metrics.print_time_source, 'm73_p0_r_minutes');
            assert.equal(metrics.filament_used_g_source, 'filament_used_g');
            assert.equal(metrics.filament_used_mm, 12764.31);
            assert.equal(metrics.filament_used_mm_source, 'filament_used_mm');
        }
    });

    it('ranks the Bambu Studio total estimated time first only for the bambu engine', () => {
        const bambu = parseGcodeMetricsStrict(BAMBU_2862_GCODE, { engine: 'bambu' });
        assert.equal(bambu.print_time_seconds, 11 * 60 + 54);
        assert.equal(bambu.print_time_source, 'total_estimated_time');
        assert.equal(bambu.filament_used_g, 0.72);
        assert.equal(bambu.filament_used_g_source, 'total_filament_weight_g');
        assert.equal(bambu.filament_used_mm, 241.2);
        assert.equal(bambu.filament_used_mm_source, 'total_filament_length_mm');
        // The same Bambu footer read with the historical ranking reports M73.
        const historical = parseGcodeMetricsStrict(BAMBU_2862_GCODE);
        assert.equal(historical.print_time_source, 'm73_p0_r_minutes');
        assert.equal(historical.print_time_seconds, 6 * 60);
        // An Orca output read as bambu would take its total; the engine decides.
        const orcaAsBambu = parseGcodeMetricsStrict(ORCA_231_GCODE, { engine: 'bambu' });
        assert.equal(orcaAsBambu.print_time_source, 'total_estimated_time');
        assert.equal(orcaAsBambu.print_time_seconds, 2 * 3600 + 29 * 60 + 41);
        // Unknown engines fall back to the historical ranking.
        assert.equal(parseGcodeMetricsStrict(BAMBU_2862_GCODE, { engine: 'other' }).print_time_source, 'm73_p0_r_minutes');
    });

    it('exposes the per-engine rankings and keeps the historical order for prusa and orca', () => {
        const ids = (patterns) => patterns.map((pattern) => pattern.id);
        assert.deepEqual(ids(PRINT_TIME_PATTERNS), [
            'm73_p0_r_minutes', 'estimated_printing_time', 'total_estimated_time', 'time_seconds'
        ]);
        assert.deepEqual(ids(BAMBU_PRINT_TIME_PATTERNS), [
            'total_estimated_time', 'm73_p0_r_minutes', 'estimated_printing_time', 'time_seconds'
        ]);
        assert.equal(resolvePrintTimePatterns('bambu'), BAMBU_PRINT_TIME_PATTERNS);
        assert.equal(resolvePrintTimePatterns('orca'), PRINT_TIME_PATTERNS);
        assert.equal(resolvePrintTimePatterns('prusa'), PRINT_TIME_PATTERNS);
        assert.equal(resolvePrintTimePatterns(undefined), PRINT_TIME_PATTERNS);
        assert.equal(resolvePrintTimePatterns('__proto__'), PRINT_TIME_PATTERNS);
        assert.deepEqual(Object.keys(PRINT_TIME_PATTERNS_BY_ENGINE).sort(), ['bambu', 'orca', 'prusa']);
    });

    it('falls back to M73 model time on bambu only when no total estimated time is present', () => {
        const content = BAMBU_2862_GCODE
            .replace('; model printing time: 5m 38s; total estimated time: 11m 54s', '');
        const metrics = parseGcodeMetricsStrict(content, { engine: 'bambu' });
        assert.equal(metrics.print_time_source, 'm73_p0_r_minutes');
        assert.equal(metrics.print_time_seconds, 6 * 60);
    });

    it('reads the Prusa FDM output shape', () => {
        for (const options of [undefined, { engine: 'prusa' }]) {
            const metrics = parseGcodeMetricsStrict(PRUSA_281_GCODE, options);
            assert.equal(metrics.filament_used_g, 24.22);
            assert.equal(metrics.print_time_seconds, 97 * 60);
            assert.equal(metrics.print_time_source, 'm73_p0_r_minutes');
        }
    });

    it('keeps a missing optional native mass explicit instead of inventing zero', () => {
        const withoutMass = PRUSA_281_GCODE
            .split('\n')
            .filter((line) => !line.startsWith('; filament used [g]'))
            .join('\n');
        const metrics = parseGcodeMetricsStrict(withoutMass, { requireFilamentGrams: false });
        assert.equal(metrics.print_time_seconds, 97 * 60);
        assert.equal(metrics.filament_used_mm, 8123.4);
        assert.equal(metrics.filament_used_g, null);
        assert.equal(metrics.filament_used_g_source, null);
    });

    it('keeps a recognized zero optional native mass explicit instead of returning zero', () => {
        const metrics = parseGcodeMetricsStrict(PRUSA_ZERO_GRAMS_GCODE, {
            requireFilamentGrams: false
        });
        assert.equal(metrics.print_time_seconds, 2 * 60);
        assert.equal(metrics.filament_used_mm, 1359.69);
        assert.equal(metrics.filament_used_mm_source, 'filament_used_mm');
        assert.equal(metrics.filament_used_g, null);
        assert.equal(metrics.filament_used_g_source, null);
    });

    it('sums unambiguous multi-extruder mass values', () => {
        const content = ORCA_231_GCODE.replace(
            '; filament used [g] = 38.4',
            '; filament used [g] = 38.4, 4.6'
        );
        assert.equal(parseGcodeMetricsStrict(content).filament_used_g, 43);
    });

    it('uses the estimated-printing-time footer on orca when M73 is absent, and the total only after that', () => {
        const withoutM73 = ORCA_231_GCODE
            .split('\n')
            .filter((line) => !line.startsWith('M73 P0 R'))
            .join('\n');
        const footer = parseGcodeMetricsStrict(withoutM73, { engine: 'orca' });
        assert.equal(footer.print_time_source, 'estimated_printing_time');
        assert.equal(footer.print_time_seconds, 2 * 3600 + 24 * 60 + 12);

        const totalOnly = withoutM73
            .split('\n')
            .filter((line) => !line.startsWith('; estimated printing time'))
            .join('\n');
        const total = parseGcodeMetricsStrict(totalOnly, { engine: 'orca' });
        assert.equal(total.print_time_source, 'total_estimated_time');
        assert.equal(total.print_time_seconds, 2 * 3600 + 29 * 60 + 41);
    });

    it('parses supported duration units', () => {
        assert.equal(parseDurationText('2h 24m 12s'), 8652);
        assert.equal(parseDurationText('1d 2h'), 93600);
        assert.equal(parseDurationText('3600'), 3600);
        assert.equal(parseDurationText('unreadable'), 0);
        assert.equal(parseDurationText('1h garbage'), 0);
        assert.equal(parseDurationText('1h 2h'), 0);
        assert.equal(parseDurationText('1msec'), 0);
    });

    it('refuses unreadable, empty-segment, and thousands-ambiguous lists', () => {
        assert.equal(sumNumericList('1.5, 2.5'), 4);
        assert.equal(sumNumericList('1.5, xx'), null);
        assert.equal(sumNumericList(''), null);
        assert.equal(sumNumericList('1,,2'), null);
        assert.equal(sumNumericList('1, ,2'), null);
        assert.equal(sumNumericList('1,234.5'), null);
        assert.equal(sumNumericList('5, 120.4'), null);
        assert.equal(sumNumericList('100,200,300'), null);
        assert.equal(sumNumericList('1234.5'), 1234.5);
    });

    it('turns a grouped mass marker into an error, not a plausible wrong mass', () => {
        const content = ORCA_231_GCODE
            .replace('; filament used [g] = 38.4', '; filament used [g] = 1,234.5')
            .replace('; total filament used [g] = 38.4', '; total filament used [g] = 1,234.5');
        assert.throws(() => parseGcodeMetricsStrict(content), (error) => {
            assert.ok(error instanceof GcodeMetricsError);
            assert.equal(error.code, GCODE_METRIC_ERROR_CODES.FILAMENT_UNPARSED);
            return true;
        });
    });
});

describe('SZ-B2 mandatory negative control: marker drift', () => {
    const DRIFTED_GCODE = ORCA_231_GCODE
        .split('\n')
        .filter((line) => !line.startsWith('M73 P0 R') && !line.startsWith('; estimated printing time'))
        .join('\n')
        .replace('; filament used [g] = 38.4', '; filament used [gram] = 38.4')
        .replace('; total filament used [g] = 38.4', '; total filament used [gram] = 38.4')
        .replace('; model printing time: 2h 24m 12s; total estimated time: 2h 29m 41s', '');

    it('drifted time format throws instead of returning zero seconds', () => {
        assert.throws(() => parseGcodeMetricsStrict(DRIFTED_GCODE), (error) => {
            assert.ok(error instanceof GcodeMetricsError);
            assert.equal(error.code, GCODE_METRIC_ERROR_CODES.TIME_UNPARSED);
            assert.equal(error.errorCode, 'SLICE_OUTPUT_UNPARSED');
            return true;
        });
    });

    it('drifted gram format throws instead of returning zero grams', () => {
        const content = ORCA_231_GCODE
            .replace('; filament used [g] = 38.4', '; filament used [gram] = 38.4')
            .replace('; total filament used [g] = 38.4', '; total filament used [gram] = 38.4');
        assert.throws(() => parseGcodeMetricsStrict(content), (error) => {
            assert.equal(error.code, GCODE_METRIC_ERROR_CODES.FILAMENT_UNPARSED);
            return true;
        });
    });

    it('zero and empty output are errors', () => {
        const zeroTime = ORCA_231_GCODE
            .replace('M73 P0 R144', 'M73 P0 R0')
            .replace('; model printing time: 2h 24m 12s; total estimated time: 2h 29m 41s', '')
            .replace('; estimated printing time (normal mode) = 2h 24m 12s', '');
        assert.throws(() => parseGcodeMetricsStrict(zeroTime), (error) => {
            assert.equal(error.code, GCODE_METRIC_ERROR_CODES.TIME_NOT_POSITIVE);
            return true;
        });

        assert.throws(() => parseGcodeMetricsStrict(PRUSA_ZERO_GRAMS_GCODE), (error) => {
            assert.equal(error.code, GCODE_METRIC_ERROR_CODES.FILAMENT_NOT_POSITIVE);
            return true;
        });
        assert.throws(() => parseGcodeMetricsStrict('   \n'), (error) => {
            assert.equal(error.code, GCODE_METRIC_ERROR_CODES.EMPTY_CONTENT);
            return true;
        });
    });

    it('the historic tolerant rule would silently return zero on the same drift', () => {
        const tolerantTime = /M73 P0 R(\d+)/i.exec(DRIFTED_GCODE);
        const tolerantGrams = /;\s*filament used \[g\]\s*=\s*([0-9.]+)/i.exec(DRIFTED_GCODE);
        assert.equal(tolerantTime ? Number(tolerantTime[1]) * 60 : 0, 0);
        assert.equal(tolerantGrams ? Number(tolerantGrams[1]) : 0, 0);
    });
});
